### ISSUE TITLE
Just installed this theme and got the following errors

### ISSUE THREAD

**Issue by walidmahade** [deviodigital/cleanblog#11]
`Notice: Undefined variable: post in /home/ubuntu/workspace/wp-content/themes/cleanblog-master/inc/template-tags.php on line 309 Call Stack: 0.0002 238752 1. {main}() /home/ubuntu/workspace/index.php:0 0.0003 239200 2. require('/home/ubuntu/workspace/wp-blog-header.php') /home/ubuntu/workspace/index.php:17 0.0536 3339848 3. require_once('/home/ubuntu/workspace/wp-includes/template-loader.php') /home/ubuntu/workspace/wp-blog-header.php:19 0.1449 3677960 4. include('/home/ubuntu/workspace/wp-content/themes/cleanblog-master/page.php') /home/ubuntu/workspace/wp-includes/template-loader.php:75 0.1449 3677992 5. get_header() /home/ubuntu/workspace/wp-content/themes/cleanblog-master/page.php:13 0.1450 3678608 6. locate_template() /home/ubuntu/workspace/wp-includes/general-template.php:45 0.1450 3678872 7. load_template() /home/ubuntu/workspace/wp-includes/template.php:531 0.1451 3692440 8. require_once('/home/ubuntu/workspace/wp-content/themes/cleanblog-master/header.php') /home/ubuntu/workspace/wp-includes/template.php:572 0.1666 3826104 9. cleanblog_header() /home/ubuntu/workspace/wp-content/themes/cleanblog-master/header.php:59 Notice: Trying to get property of non-object in /home/ubuntu/workspace/wp-content/themes/cleanblog-master/inc/template-tags.php on line 309 Call Stack: 0.0002 238752 1. {main}() /home/ubuntu/workspace/index.php:0 0.0003 239200 2. require('/home/ubuntu/workspace/wp-blog-header.php') /home/ubuntu/workspace/index.php:17 0.0536 3339848 3. require_once('/home/ubuntu/workspace/wp-includes/template-loader.php') /home/ubuntu/workspace/wp-blog-header.php:19 0.1449 3677960 4. include('/home/ubuntu/workspace/wp-content/themes/cleanblog-master/page.php') /home/ubuntu/workspace/wp-includes/template-loader.php:75 0.1449 3677992 5. get_header() /home/ubuntu/workspace/wp-content/themes/cleanblog-master/page.php:13 0.1450 3678608 6. locate_template() /home/ubuntu/workspace/wp-includes/general-template.php:45 0.1450 3678872 7. load_template() /home/ubuntu/workspace/wp-includes/template.php:531 0.1451 3692440 8. require_once('/home/ubuntu/workspace/wp-content/themes/cleanblog-master/header.php') /home/ubuntu/workspace/wp-includes/template.php:572 0.1666 3826104 9. cleanblog_header() /home/ubuntu/workspace/wp-content/themes/cleanblog-master/header.php:59`

**Comment by robertdevore** [comment]
Looking this over but I'm not sure what type of error is happening. Have you been able to replicate this same issue on a different server set up?

**Comment by walidmahade** [comment]
No, I only tried once in cloud9.

**Comment by walidmahade** [comment]
the website loads fine,works fine, but in the head those error lines shows up.

**Comment by robertdevore** [comment]
hmm ... Is there a way for you to test the theme out on a different server, or a clean cloud9 server?

**Comment by walidmahade** [comment]
All right, I tried it on nitrous in a fresh install, It works fine.
Sorry for bugging you. I should have been more patient.

**Comment by robertdevore** [comment]
No sweat, I'm happy it got sorted out!
