### ISSUE TITLE
Undefined variables with Bedrock

### ISSUE THREAD

**Issue by alejobit** [deviodigital/cleanblog#12]
Hi, I'm using [Bedrock](https://roots.io/bedrock/) for WordPress boilerplate and I'm getting the followings warnings:

**In homepage**

```
Notice: Undefined variable: author_id in cleanblog/inc/template-tags.php on line 90
Notice: Undefined variable: author_id in cleanblog/inc/template-tags.php on line 91
Notice: Undefined variable: author_id in cleanblog/inc/template-tags.php on line 92
```

**In single page**

```
Notice: Undefined variable: post in tcleanblog/inc/emplate-tags.php on line 284
Notice: Trying to get property of non-object in cleanblog/inc/template-tags.php on line 284
```

**Comment by robertdevore** [comment]
Thanks for bringing this to my attention. I'll check into it as soon as possible, but in the meantime if you know of a solution, feel free to create a pull request 👍

**Comment by robertdevore** [comment]
Updated the code to remove these notices in [this commit](https://github.com/deviodigital/cleanblog/commit/bc265f9b0f359ebd2f84b4b438baea297964f1c0)
