### ISSUE TITLE
Social Links not centered in footer

### ISSUE THREAD

**Issue by caelen-feller** [deviodigital/cleanblog#13]
78b4ed28064a5f21d973643636e9c347a414c121 causes the social links to not be centered.
![2017-09-01-184453_1920x1080_scrot](https://user-images.githubusercontent.com/3074658/29981538-e879d794-8f45-11e7-8358-878b9c36ba3e.png)

Why was the override necessary in the first place?

**Comment by robertdevore** [comment]
Thanks for pointing this out. Added in an [update](https://github.com/deviodigital/cleanblog/commit/2745a46f8d1c2343b2778ce1c03d08ab727bfae8) that fixes this issue, removing the left margin that was causing it to be moved to the right.
