### ISSUE TITLE
Add Anchor tag in the Home Intro area can't find it.

### ISSUE THREAD

**Issue by sparkle-core** [deviodigital/cleanblog#14]
In the index.php file I see the do_action('cleanblog_index_top'); and I can't find where it's coming from to edit the homeIntro div section.

**Comment by robertdevore** [comment]
`cleanblog_index_top` is there for you to add custom content within that space, it doesn't control any of the actual theme content that's already in place.

If you're looking to edit the home intro section, you can do that in the `inc/template-tags.php` file, starting at [line 273](https://github.com/deviodigital/cleanblog/blob/master/inc/template-tags.php#L273)

**Comment by sparkle-core** [comment]
Awesome. Thank you!
