### ISSUE TITLE
Published date link redirects back to post

### ISSUE THREAD

**Issue by braheem** [deviodigital/cleanblog#2]
The published date link that appears under the post title links to the post itself. I am assuming that if it should link to anything, it would be an archive of posts for that date/month?

**Comment by robertdevore** [comment]
If I'm not mistaken, it's the code that came with the _s theme. I agree though, it shouldn't link back to the post, and actually shouldn't link anywhere (I don't personally think).

Looking into a fix for it now. Thanks for bringing it to my attention.

**Comment by braheem** [comment]
Not a problem. I would agree with having it not link anywhere as that is my personal preference as well.

**Comment by robertdevore** [comment]
Editing out the link now. Thanks again for pointing this out.
