### ISSUE TITLE
Wordpress admin bar overlaps navigation bar

### ISSUE THREAD

**Issue by kartikhimself** [deviodigital/cleanblog#3]
![screen shot 2015-11-22 at 3 22 27 pm](https://cloud.githubusercontent.com/assets/2084748/11323129/1ca7198e-9130-11e5-84a8-88b520d2e3ec.png)

**Comment by robertdevore** [comment]
Thanks for bringing this up. I didn't have the admin bar active when testing the theme, but I see the problems. I'll be pushing an update either later today or tomorrow, I just need to do some testing before the push.

**Comment by kartikhimself** [comment]
Great devio ! I love the theme irrespective. It is beautifully designed and has very good performance. Thanks. Keep up the great work ! :)

**Comment by robertdevore** [comment]
Sorry that it took a while longer than I thought it would, but I've committed an update to the style.css file that fixes the WP admin bar style issue.

**Comment by kartikhimself** [comment]
Hi devio i was still facing the same issue. I have pushed an update to style.css after which its working fine. Please review and merge.
