### ISSUE TITLE
External Featured Image

### ISSUE THREAD

**Issue by stal1n274** [deviodigital/cleanblog#4]
I tried to use several wordpress plugin that allows to use external featured image, but all of them require **(get_)the_post_thumbnail** function that is absent in your theme.
Could you please add support of this feature? 
Thank you in any case for such beautiful and simple theme!

**Comment by robertdevore** [comment]
Can you post up some more info about what you're trying to do?

**Comment by stal1n274** [comment]
Wordpress gas a feature that allows to set the Featured Image for the post or page. This image will be in the header with paralax effect a in your theme.
![image](https://cloud.githubusercontent.com/assets/5851581/13544482/06e493f6-e27f-11e5-85e0-6c4c38367e3f.png)

Basically user should upload imahge to host, but thege are plugin that allow to use images from anywhere as the featured image of pages and posts. For example: https://wordpress.org/plugins/external-featured-image/

Information on wordpress site:
https://en.support.wordpress.com/featured-images/
https://codex.wordpress.org/Post_Thumbnails

The issue is that images from another site aren't showed in cleanblog theme.

**Comment by robertdevore** [comment]
OK, so you switched themes and the featured images are no longer showing? Or are you trying to import content from another site to a site that uses the Clean Blog theme?

**Comment by stal1n274** [comment]
I switched themes and images that were uploaded to server have been showed. 
No problems with images on the server.

But I cannot see feature image a picture from the URL using plugin "Nelio External Featured Image".

**Comment by robertdevore** [comment]
OK, I understand now. Thanks for the explanation. I will look over how easy it'd be to update the `get_the_post_thumbnail` into the theme.

In the meantime, you can use the [child theme](https://github.com/deviodigital/cleanblog-child) and edit the files yourself if it's super time sensitive.

**Comment by stal1n274** [comment]
Thanks Robert!
I've already created child theme from your cleanblog-master, but I don't have a skill to fix this issue.

**Comment by stal1n274** [comment]
Hi Robert,

Have you had a chance to look into this?
