### ISSUE TITLE
Make feature image dark (automatic or optional setting)

### ISSUE THREAD

**Issue by kuldeepdhaka** [deviodigital/cleanblog#5]
Please provide a option to make feature image dark.
If a image with alot of white content is used, the heading is very hard to read. (since the font is white)

Also, when sharing on social media and the featured image is used as big image (im talking of https://dev.twitter.com/cards/types/summary-large-image)
Problem is, on social media this require manual work or look bad.

source: `inc/template-tags.php`

```
<header class="intro-header" style="background-color: #404040; background-image: url('<?php echo $feat_image; ?>')">
        <div style="background-color: rgba(0, 0, 0, 0.5)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><?php single_post_title(); ?></h1>
                        <?php if ( function_exists( 'the_subtitle' ) ) {
                            the_subtitle( '<h2 class="subheading">', '</h2>' );
                        } ?>
                        <span class="meta"><?php cleanblog_posted_on(); ?></span>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </header>
```

Note: changes need to be made to all places where there is a background image `background-image:` in `inc/template-tags.php`. the above is only an example

**Comment by kuldeepdhaka** [comment]
Work for me!
https://github.com/kuldeepdhaka/cleanblog/commit/cef15437fa45c58ae5dd94a233817f7dd11129a0

**Comment by robertdevore** [comment]
@kuldeepdhaka In the theme customizer, there's already an option to make the featured image darker, with a simple on or off radio button.

![customizer](https://camo.githubusercontent.com/14d196ed4346d4ba5a9c5c6dfe5b9eb49dea03ec/687474703a2f2f7777772e726f626572746465766f72652e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30322f636c65616e626c6f672d6461726b656e2d6865616465722d6e6f2e6a7067)

**Comment by robertdevore** [comment]
Going to close this now.

**Comment by kuldeepdhaka** [comment]
yes!
