### ISSUE TITLE
What resolution of featured image is recommended to use?

### ISSUE THREAD

**Issue by stal1n274** [deviodigital/cleanblog#6]
When I set up featured image to post it is resized and cropped.
What resolution of featured image is recommended to use to best looking in the blog? e.g. 1024x768

**Comment by robertdevore** [comment]
The height of the background image space is around 450-500px depending on the title of the page/post. The width would depending on the browser size you're viewing the page in. A PC laptop will show different than a Mac desktop, for instance.

**Comment by stal1n274** [comment]
Thank you.

**Comment by robertdevore** [comment]
:+1: 

closing this now.
